### ISSUE TITLE
View of the order page

### ISSUE THREAD

**Issue by ANeuralDip** [akabikas/pizza-react-app-v1#14]
The order page looks great, I just cannot scroll to the end of it, with the only fix being zooming out. I believe it might be a CSS issue, please look into it.

![order page not scrollable](https://user-images.githubusercontent.com/72255374/229445606-8e47b787-3954-448f-8de6-27758adf0595.png) - my view of the page

**Comment by akabikas** [comment]
Fixed the scroll Issue by changing overflow property.
